package com.ctc.model;
// Generated Apr 5, 2015 9:11:56 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AddressJoin generated by hbm2java
 */
@Entity
@Table(name="address_join"
    ,catalog="ctcfact"
)
public class AddressJoin  implements java.io.Serializable {


     private String uncleanedAddress;
     private String cit;
     private String state;
     private String result;
     private Integer httpStatus;
     private Integer httpTime;
     private Date ts;
     private Integer id;

    public AddressJoin() {
    }

	
    public AddressJoin(String uncleanedAddress) {
        this.uncleanedAddress = uncleanedAddress;
    }
    public AddressJoin(String uncleanedAddress, String cit, String state, String result, Integer httpStatus, Integer httpTime, Date ts, Integer id) {
       this.uncleanedAddress = uncleanedAddress;
       this.cit = cit;
       this.state = state;
       this.result = result;
       this.httpStatus = httpStatus;
       this.httpTime = httpTime;
       this.ts = ts;
       this.id = id;
    }
   
     @Id 
    
    @Column(name="uncleaned_address", unique=true, nullable=false, length=99)
    public String getUncleanedAddress() {
        return this.uncleanedAddress;
    }
    
    public void setUncleanedAddress(String uncleanedAddress) {
        this.uncleanedAddress = uncleanedAddress;
    }
    
    @Column(name="CIT", length=20)
    public String getCit() {
        return this.cit;
    }
    
    public void setCit(String cit) {
        this.cit = cit;
    }
    
    @Column(name="STATE", length=20)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="result", length=65535)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    
    @Column(name="http_status")
    public Integer getHttpStatus() {
        return this.httpStatus;
    }
    
    public void setHttpStatus(Integer httpStatus) {
        this.httpStatus = httpStatus;
    }
    
    @Column(name="http_time")
    public Integer getHttpTime() {
        return this.httpTime;
    }
    
    public void setHttpTime(Integer httpTime) {
        this.httpTime = httpTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }
    
    @Column(name="id")
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


